### ISSUE TITLE
[Question]: Radio Groups / Tab Groups?

### ISSUE THREAD

**Issue by bennypowers** [leobalter/cross-root-aria-delegation#4]
How does this proposal affect cases like radio groups or tab groups, which today require users to place all of the related elements in the same root.

If the proposal does not affect those cases, how might it interact with a future proposal which does?

Thank you Leo for putting this proposal together.

**Comment by leobalter** [comment]
I don't know yet. I'll take a look and if I don't have any answer I'll forward the question to the AOM group next week.

**Comment by nolanlawson** [comment]
In this same vein, I would wonder about [the combobox pattern](https://www.w3.org/TR/wai-aria-practices-1.1/#combobox), and in particular `aria-activedescendant`. Imagining that the custom element structure is something like this:

```html
<x-combobox>
  #shadow-root
    <input aria-activedescendant="foo">
</x-combobox>
<x-listbox>
  #shadow-root
    <x-listitem id="foo"></x-listitem>
    <x-listitem id="bar"></x-listitem>
    <x-listitem id="baz"></x-listitem>
<x-listbox>
```

... it's not clear to me how the combobox could reference an individual list item using `aria-activedescendant`. The `<x-combobox>` could delegate `aria-activedescendant`, but it still wouldn't have access to the `foo` `id` because it's inside the `<x-listbox>`'s shadow root. Does this proposal cover this scenario?

**Comment by leobalter** [comment]
Thanks @nolanlawson! This is a slightly more complex case that also shows some limitations of the current proposal.

The cross-root aria delegation allows only a single layer of delegation. so I'm afraid we'd be still be short to resolve connecting the input from `x-combobox` to the shadow rooot of `x-listbox`.

For that, we might need bigger work within the AOM's ID reflection, which I consider orthogonal to this current proposal.

**Comment by gonzalocordero** [comment]
@leobalter may I suggest adding, a note on your proposal around how not all cross-shadow use cases are covered so that contributors understand the scope.

**Comment by leobalter** [comment]
it makes sense, @gonzalocordero. I'll do it!

**Comment by mrego** [comment]
This is now included in the [updated explainer](https://github.com/leobalter/cross-root-aria-delegation/blob/main/explainer.md#combination-of-both-proposals-issue-4), that goes over the 2 proposals delegation and reflection, and should look into how they both combine in some of these more complex use cases.

**Comment by mrego** [comment]
Let's merge this issue into #14 as it has some more content discussion, but they end up talking about the same topic.
