### ISSUE TITLE
General questions, IDL and delegation of something that isn't provided

### ISSUE THREAD

**Issue by leobalter** [leobalter/cross-root-aria-delegation#7]
Questions by @bkardell , originally from #6

- Is the first code example missing a `<template>`
- Where do these get added in IDL?
- What happens if you delegate something and it isn't provided? What if it is provided implicitly? (like, using a <label> itself?)
- Are all of the names. simply boolean attributes? That is, their mere presence is true? ariadelegateslabel=false - what happens - with that?

**Comment by leobalter** [comment]
> Is the first code example missing a `<template>`

this is now improved. I first used an example simulating the rendered shadow-root but now the examples are reusable if someone copy and paste the HTML and JS parts.

> - Where do these get added in IDL?
> - What happens if you delegate something and it isn't provided? What if it is provided implicitly? (like, using a itself?)

I don't have these answers yet.

> Are all of the names. simply boolean attributes? That is, their mere presence is true? 

They are boolean attributes.

> ariadelegateslabel=false - what happens - with that?

IDK, I'll see that.

**Comment by bkardell** [comment]
fwiw https://html.spec.whatwg.org/#boolean-attributes is what I meant, specifically.  There are attributes which work both ways, I was just asking which it was intended. Sometimes the string false works, sometimes it is "a boolean attribute" by that definition

**Comment by mrego** [comment]
Let's move this to different issues, one for the [IDL question](https://github.com/leobalter/cross-root-aria-delegation/issues/20) and another for what happens when you [delegate something that isn't provided](https://github.com/leobalter/cross-root-aria-delegation/issues/21).

About the booleans, we might end up going with attributes that allow a list, so I guess that can be discussed as part of #3.
